version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: http-proxy-middleware
    versions:
    - 1.0.6
    - 1.1.0
    - 1.1.1
    - 1.1.2
    - 1.2.0
    - 1.3.0
  - dependency-name: three
    versions:
    - 0.125.1
    - 0.125.2
    - 0.126.0
    - 0.126.1
    - 0.127.0
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
    - 9.8.6
  - dependency-name: webpack-bundle-analyzer
    versions:
    - 4.4.0
  - dependency-name: ora
    versions:
    - 5.3.0
  - dependency-name: vue-loader
    versions:
    - 16.1.2
  - dependency-name: semver
    versions:
    - 7.3.4
  - dependency-name: babel-loader
    versions:
    - 7.1.5
